# =======================================#
# -----------DUMBARTON THEME-------------#
# ----------------By: Tyler Butler-------#
#-----------------https://tbutler.org----#
#========================================#

# =======================================#
# -----------BASE SETTINGS---------------#
#========================================#

title: Aagam Shah 
email: aagam2@illinois.edu
description: # a minimalistic jekyll theme for academics
baseurl:                                      # the subpath of your site, e.g. /blog
url: "https://aagamrshah.github.io/"          # the base hostname & protocol for your site, e.g. http://example.com
image:           # used to generate site link preview
image_alt: # A minimalistic jekyll theme for academic    # image description
google-tag: G-B0CD0C5TDR

# =======================================#
# -----------SITE SETTINGS---------------#
#========================================#: 
author: Aagam Shah 
profile_image: /assets/img/avatar/aagam_headshot.jpg #/assets/img/avatar/avatar.jpeg 
occupation: 
snippet:
twitter: 
github: aagamrshah
linkedin: aagamshah228
stackoverflow:
website: https://aagamrshah.github.io
codepen: 
medium: 
email: aagam2@illinois.edu
keybase:
pgp: 
ctftime: 
phonenumber: 

#========================================#
# --------- UI THEMES -------------------#
#========================================#
ui_theme: abyss                                 # Create your own theme by setting options in _data/themes.yml


# =======================================#
# -----------BLOG SETTINGS---------------#
#========================================#

tags:  # post jekyll styleguide ipsum
twitter-widget: false # true,false                  # Used to show your twitter timeline on blog home page

comments: false                                     # Used to enable comments on blog posts
gitalk_client_id:             
gitalk_client_secret:    
gitalk_repo:
gitalk_owner: 
gitalk_admin: 
gitalk_distraction_mode: false

# =======================================#
# -----------THEME SETTINGS--------------#
#========================================#

nav-color: "#304C89"                                 # options: light, dark, transparent, primary, custom | Change the color of the navbar
footer-color: "#304C89"
color-scheme: "#304C89"                              # options: demo | changes color scheme based on preset values 
card-color: "#304C89"                                # Used on cards like the home highlights section
nav-dIcon: "fas fa-caret-down"                       # Change the navbar dropdown (for mobile or small screen sizes) to any fontawesome icon. for a list of icons visit https://fontawesome.com/ 
animate: true                                        # false or true, uses animate.css to animate certain functions

# =======================================#
# -----------HOME PAGE  SETTINGS --------#
#========================================#
home_option: education                               # options: education, skills, timeline, interests
home_option_2: interests                             # options: education, skills, timeline, interests

# =======================================#          # These  settings are for demo purposes only, things like 
# -----------HELP SETTINGS---------------#          #     popup toasts and tooltips designed to help new 
#========================================#          #     developers as they look into using this theme      
help_tips: false                                    # options: true, false  | use false to disable these for production mode


# =======================================#
# -----------BUILD SETTINGS--------------#
#========================================#
theme: 
markdown: kramdown

kramdown:
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-scholar
  - jekyll-environment-variables
sass:
  sass_dir: _sass
  style: compressed


include:
  - _myprojects
  - _posts

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# =======================================#
# -----JEKYLL SCHOLAR SETTINGS-----------#
#========================================#
scholar:
  last_name: Shah
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: 
  query: "@*"

# =======================================#
# ------------CDN SETTINGS---------------#
#-------------Used to generate icons-----#
#========================================#
font_awesome_id: b31343d87a                       # Register for free at https://fontawesome.com/ to get your id


# =======================================#        # For more information about these settings, visit https://htmlhead.dev #
# ------------META TAG SETTINGS----------#
#========================================#
google-site-verification: G-B0CD0C5TDR                         #<meta name="google-site-verification" content="verification_token"><!-- Google Search Console -->
yandex-verification:                              #<meta name="yandex-verification" content="verification_token"><!-- Yandex Webmasters -->
msvalidate:                                       # meta name="msvalidate.01" content="verification_token"><!-- Bing Webmaster Center -->
alexaVerifyID:                                    # <meta name="alexaVerifyID" content="verification_token"><!-- Alexa Console -->
pinterestdomain_verify:                           #<meta name="p:domain_verify" content="code_from_pinterest"><!-- Pinterest Console-->
norton-safeweb:                                   # <meta name="norton-safeweb-site-verification" content="norton_code"><!-- Norton Safe Web -->
detectphone: yes                                  # yes or no. Disable automatic detection and formatting of possible phone numbers 
x-dns-prefetch-control: on                        # on or off. Completely opt out of DNS prefetching by setting to "off"
fbappid:                                          # Facebook OpenGraph 




pgp-key: "-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBGQ54xMBEACjmeSXCf75H2CyiTbnTHClUsU3D22H4jtFn1qWmlzw6EWZuMEk
ooCNjO4IhiDRlul4iK4mwIGvwrsHjHeB234vu79Svgn+FpSBx+4OVEL7i+pv0QmY
ffqrREdGwnH7hwx/Ucp6lJTt8nCD0GFQhD/HumpyH8fAoeQwrB9X8CWoIn3jK6LY
CpB89yZ/+8jksd/41zTbxcnf3mZNImRW8yw8Y+ZZUKRTv/gmCxEmjcdTKu4FWlRo
zklFfmdAKatEsSJSMhckOKCcJeOaRPN4k6NK7VOEO2c2+JmeaDJcKnPt6RTn6+hy
6OHo68Cw7fhbusYbeN56tY4W5MRYTXYYSTmctRAzuVMCFrqKF1auQPIqb7q0ou0b
5FaC/GeDrpo5Qog3SfN8eXSltvLdN++0GCkRW4j1D4w3MsCMa0ZpYBNB+Q2M5YgQ
vwZ4gIM3MjRHDIqauFKArwinCRfci7IQXtqP+GSC7Xt5nnnyJvxA5u02eZbzCUZV
HxjkJ1OTSPmZYUkHf2z9FEd88Fd1FHtQB6bASNu0t3BPREERxvWlh/px2FXGiIKa
hgYl0XM7kjTqY2RsFXRR/RcBlIKFnfXNzaRg2hXIwBQQ9g73lQZlpknJAL8YSU7f
6ojtKAozkYEVYRYvx0Kd6uSMkPdQCzQSF3b7Yezs+qnHp/AHuuhtDT7WfQARAQAB
tB1BYWdhbSBTaGFoIDxhcnN0cnNAZ21haWwuY29tPokCUQQTAQgAOxYhBDDWx/Sy
puzpXbItltmpKlapmI9sBQJkOeMTAhsDBQsJCAcCAiICBhUKCQgLAgQWAgMBAh4H
AheAAAoJENmpKlapmI9sOBcP/3E0JTQIiXuNTd87YwgDdvHYHO+8PnMsuAGCDXR6
WEfVNC8i0b0hGccptk0K7fJredeD0Qxz/BcPx95JQaLC1K51ZGYY4m1FGXIKR5PD
Vowq7BVg0kcHyziUHkelccSzwTI1nKYpiA11FbKhIFSfMg4v2XtAjqwZZccm5RMz
3RaoOBPADqKP6bt6cZMnXP77bDjkJn0ZPU+79BGQxVstjbHc3Sx/QvPiVEmEN8MY
vIx3nicAYX4sKsuGexAB/sur5DDHr7IgjFCQt+Ih6blC8LBqJzdzf3DhbARNXTQB
9hjwGqraYKqW9IWIdFRWGyvGBrob+n+HWBGvNn/+27+GcH/RN6J7eOUIPSepI7EI
Qt5KdWPn2kv3Cy6nlCiWIsfEfT9sEEskeD7ZByqjlSlRSSHhPdavdeaH1iTkBg4G
DUgI7E0Q7PkZ6RVzPC92mBVtPrK9cI1F27yE911lswxjKRyUGo3TZHw835JV+DLo
hvzfsgovHwo5kq/Ef7QdILXCVXyxabpc1Ud18pDwd8P1nkiOT+hGb0K48ntrSCkL
Vh65tcSMj3rBV5phwDYaEiyEOQ5UupzgIbImHnzNtEg7xTnEnmCNjb0tT6VkpsV/
C9tGA9iBk0qnZR//uNFETk+1fWZgWiSd3NIzWCI7BVQWVKWOhME5UVrh461A5qqW
cysiuQINBGQ54xMBEADOe5onFfotxzqpqEzePaFVB5pAht6M7yiQBHRroYCzqTa6
WegizyL11tjDuA/wT5xm38fz0N4f6XebefpDfdVr1Aav2+E/TifzohW6S/k+ZVCX
45vBcNemW0fDOzhk5mYUYe0OlJc/4ATEScHpKzHrdFPqmS6SAt5KDHO4wwhDNCwR
s/+lLLySBcGG9ZPrvV4LbMjk/Yj4r2IUgIJ/+NIBIO+rzNDuAjSfXb9cpJpWR6YG
SAs05aZ+iyQj2qSPpih+a8QgqJgOlMlsUBJNJLBcbHFxAqdBHd8h9npA6RCUZXqL
xnszxP0gkwiU0Zu9PyNU/GrRqttKbYZMWQffYLPY9i7mS0ayiReIx51D5tI7KwkM
c/SfY5woT1bgfIjzOojaC/5bhsQuDc4mRKaS7XxRA8JsmOtChtAMVpWwCFAQyI5O
rTu1eaIJqB49nxPWFP2d/Hkjd95SvP5CIxrmPyy0RJvEr0zoYoBe6sA5naUJSA5e
AVByqfG0Z2a37fJVhUXx8JnlnOA1vr3B8zVTzlsReLdIV+pRhEjEdmun38ByxCZB
6CkwincFF0oowN/IqbBYOwCl3vI6cgVAHz+p8h1kbvYoA7jdhFxgBc8RGX0zN9rH
Mf7ERlpPn4E+yIjQ2/rT0rTLf+uQB5drvudD13q1sUSlBT1GIz7xEqITzz8aFwAR
AQABiQI2BBgBCAAgFiEEMNbH9LKm7Oldsi2W2akqVqmYj2wFAmQ54xMCGwwACgkQ
2akqVqmYj2yAmw//QnIY2bH74eRJykLJGdN3nfBCOMmbUnuSU6eJcK8yWD6eE6JT
L3aRL5Hiy7zfgLmcLzgNIzWsC0ZETbVcbvnDSfqMquzc7N47y+SuDv1k0DxGPbIA
N4gDD7U80YoUcIg+YUN7w7TKZ31Cj7Zti/0N2nqpNP7GCraLZc3XUTarup4EMr3n
UEd3wh+bQoi68P8jFEiOUN4AGKWyivnsjaLwFEIvrLCcu++2w+EbkOxkaqcWiUmX
Qg9qaY2gT3Ztx8+8ecR4ljsD4lyvswhMZbsh6L1fCIciwf/3t1zcEAuu6KtY5bef
+Ml8q0NNVtCXIjwY8oKtl4x5UaBzArLQTpvddjZ9RVgYF6s9y6Olqove40sZrzt6
EXfg4RDpIxyuuSGZWKWG2B2YuaL9Q2Yoe7vsgElPWCVafIEJJA0hathSH/OuS86b
lcj2C+PHHXzmJf+j9fwtmV7uVY1W6oHYph8TQlMjfZvKCZSPLCv2GXxv61Wy9dhe
wYzOQG+q/GD3UlRjyeLLDbjhh58pXTTllGXWLkDhJKGhOHYOPeSS+AhGFklLnlbb
CrFF0xItUyQNKiyNmt4H3BlpKO3+avhRxmxvsCzk+UnKWGgnrJFoElX1dt6X+5mQ
gnx/PQxwIwXuWhWnw5ciH/RblV5Y0r+jdCLAIcSp8k+3u6GjLv1HB6eEBmM=
=t3xu
-----END PGP PUBLIC KEY BLOCK-----"