# =======================================#
# -----------DUMBARTON THEME-------------#
# ----------------By: Tyler Butler-------#
#-----------------https://tbutler.org----#
#========================================#

# =======================================#
# -----------BASE SETTINGS---------------#
#========================================#

title: Aagam Shah 
email: aagam2@illinois.edu
description: # a minimalistic jekyll theme for academics
baseurl:                                       # the subpath of your site, e.g. /blog
url: "https://aagamrshah.github.io/"          # the base hostname & protocol for your site, e.g. http://example.com
image:           # used to generate site link preview
image_alt: # A minimalistic jekyll theme for academic    # image description
google-tag: G-B0CD0C5TDR

# =======================================#
# -----------SITE SETTINGS---------------#
#========================================#: 
author: Aagam Shah 
profile_image: /assets/img/avatar/aagam_headshot.jpg #/assets/img/avatar/avatar.jpeg 
occupation: 
snippet:
twitter: 
github: aagamrshah
linkedin: aagamshah228
stackoverflow:
website: https://aagamrshah.github.io
codepen: 
medium: 
email: aagam2@illinois.edu
keybase:
pgp: 
ctftime: 
phonenumber: 

#========================================#
# --------- UI THEMES -------------------#
#========================================#
ui_theme: abyss                                 # Create your own theme by setting options in _data/themes.yml


# =======================================#
# -----------BLOG SETTINGS---------------#
#========================================#

tags:  # post jekyll styleguide ipsum
twitter-widget: false # true,false                  # Used to show your twitter timeline on blog home page

comments: false                                     # Used to enable comments on blog posts
gitalk_client_id:             
gitalk_client_secret:    
gitalk_repo:
gitalk_owner: 
gitalk_admin: 
gitalk_distraction_mode: false

# =======================================#
# -----------THEME SETTINGS--------------#
#========================================#

nav-color: "#304C89"                                 # options: light, dark, transparent, primary, custom | Change the color of the navbar
footer-color: "#304C89"
color-scheme: "#304C89"                              # options: demo | changes color scheme based on preset values 
card-color: "#304C89"                                # Used on cards like the home highlights section
nav-dIcon: "fas fa-caret-down"                       # Change the navbar dropdown (for mobile or small screen sizes) to any fontawesome icon. for a list of icons visit https://fontawesome.com/ 
animate: true                                        # false or true, uses animate.css to animate certain functions

# =======================================#
# -----------HOME PAGE  SETTINGS --------#
#========================================#
home_option: education                               # options: education, skills, timeline, interests
home_option_2: interests                             # options: education, skills, timeline, interests

# =======================================#          # These  settings are for demo purposes only, things like 
# -----------HELP SETTINGS---------------#          #     popup toasts and tooltips designed to help new 
#========================================#          #     developers as they look into using this theme      
help_tips: false                                    # options: true, false  | use false to disable these for production mode


# =======================================#
# -----------BUILD SETTINGS--------------#
#========================================#
theme: 
markdown: kramdown

kramdown:
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-scholar
  - jekyll-environment-variables
sass:
  sass_dir: _sass
  style: compressed


include:
  - _myprojects
  - _posts

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# =======================================#
# -----JEKYLL SCHOLAR SETTINGS-----------#
#========================================#
scholar:
  last_name: Shah
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: 
  query: "@*"

# =======================================#
# ------------CDN SETTINGS---------------#
#-------------Used to generate icons-----#
#========================================#
font_awesome_id: b31343d87a                       # Register for free at https://fontawesome.com/ to get your id


# =======================================#        # For more information about these settings, visit https://htmlhead.dev #
# ------------META TAG SETTINGS----------#
#========================================#
google-site-verification:                         #<meta name="google-site-verification" content="verification_token"><!-- Google Search Console -->
yandex-verification:                              #<meta name="yandex-verification" content="verification_token"><!-- Yandex Webmasters -->
msvalidate:                                       # meta name="msvalidate.01" content="verification_token"><!-- Bing Webmaster Center -->
alexaVerifyID:                                    # <meta name="alexaVerifyID" content="verification_token"><!-- Alexa Console -->
pinterestdomain_verify:                           #<meta name="p:domain_verify" content="code_from_pinterest"><!-- Pinterest Console-->
norton-safeweb:                                   # <meta name="norton-safeweb-site-verification" content="norton_code"><!-- Norton Safe Web -->
detectphone: yes                                  # yes or no. Disable automatic detection and formatting of possible phone numbers 
x-dns-prefetch-control: on                        # on or off. Completely opt out of DNS prefetching by setting to "off"
fbappid:                                          # Facebook OpenGraph 




pgp-key: "-----BEGIN PGP PUBLIC KEY BLOCK-----
xsBNBGQnWhcBCACvwybEpmWAZFLJ9ALzSY351IAR0a7XrqZs9m/IAYQwNaX5FvJw
ieoMOxE9x86ZbvZ7ghvsFOJjdhc6diQbWhhmYd2wKMnrn4bmM97SMuzfy6RtBIde
M7G4BthE+3I6Qe1o1rqOYzW1bz+5EFi4e2Frch9HXPHc7hoPgfQ5I3ghyNIEPIa/
WyTncJNh7DIjYTKSwWMdWW/Dz53FKChHX17sAmfEWkPW+uhV65JikY7t5LjC5tMy
16bCp3W0kVBiXuPYQdm9eiqcwm2xjL+bHaRGXqRrNEwZS1uq49N++7SIPHgDHPgD
JC0/8BEvq9oHcs4sXDSest0JlsiKbzsvcQHfABEBAAHNHUFhZ2FtIFNoYWggPGFy
c3Ryc0BnbWFpbC5jb20+wsB6BBMBCgAkBQJkJ1oXAhsvAwsJBwMVCggCHgECF4AD
FgIBAhkBBQkAAAAAAAoJEHgxccsaz3JK1tIH/1UZVOJ/6q1fMeaB5/EHQtt6d6EJ
/lVN0thg1AQXWaDJ5xjmtFw0k+P00YnAl69Hfw3/cMlCMx4Fg2SHd3lFCVPNjLuI
+btCKeRgtA7uDyiIFYMBV+/8gwb3kXeZE0XgeCD9JIfB6cgMEEqpdOkExnB8eyiW
H2rsk+Q+7ndsiarIuhcsn/6Qclk0IkxD6udzOBu72R8AJiChxMD3uNU7iB+Eo2Ki
kRUij8iS7fkKvqBFLjc6/g+utu6WkRiv6yrs+9dauOkEJM7u29quvaUxiDg1j2ky
nJJmItSdtZBZqclW0ooEXmYFoCp5nQ+rKC98q0Qiw5p2La74rPwh/eLlM8LOwE0E
ZCdaFwEIAMSAEAwzv770UiO1jwfp3Ne5yxGRdd0FZbN9LqRCZQ1R9c/cWWvj1gdr
QBerXxGYt4lKFFVWe5iYgw4iuhSg+CaM4Yxa1wiTQDbDYbtKB0zw9+CVgkGxasyT
h+ib0QoMH3YjxHZJpw8HHMiBeQ2eIyTgZgkMB365BWa5qRRjcbJ1isgMl+EV5iVQ
xh4jf6QOZhhAhjWNSoAP0DpDUpAbGjkDPp3ByZlEgWMDlBBnFoE8UV0ttx/XA4ud
5GkVybLdtUrIcAgj7WiSmSkCVI95IatcGWfWbpPQ4BrFL7tgO/yTUWbNwX8CLRmJ
tdQJp/Eh7hxm0PQQ1i/nAoifVVaUKU0AEQEAAcLBhAQYAQoADwUCZCdaFwUJAAAA
AAIbLgEpCRB4MXHLGs9ySsBdIAQZAQoABgUCZCdaFwAKCRBo+nrTV5vEd8AgB/4o
tVxq7p0XLmIkV5TAOH61/CCSDcPrGmdyELBkXNXzPElkeX+SQ34DCdf355RtxakJ
1qXTKQROsMlNnE52GlWnJDDizPCfrQcIJUlK4MDVVqcyZP+EV+tDQfQUbn07Rcmi
Ts/cdPKL1r6KHbFujAyL9cDiruIwxQa2a6OWtZZFLgOS4GSfMnXpqgsnjrHcw0fh
TWBNOZP7dopwCZeC30slExrExxyIYMCGCQVnPGywAvS7vp6RQ2IhFwR5dEq4ym50
84q2O9hEnN8vnssSSodiD93jmPX3ux1ynMkScU4j3lzLWeBqXbWsdYJi45RZAQdZ
jHeTjGw44Lq6O3zxm/0YF1wH/RVXowfc7UZSAm09ntBWH989eKgd4mWjxCW+E7ey
LcdqDZ4NpwZsNn5EhIhCNXLfCJ4SP1RqaUyS0KoH8NwUOFiXfsvQhdmdMHk+h4q8
aJYw+KbCFiehPwybhWHBtr8hLxP6Qu6DR3qJATAWfu6vn4aVwBPuNoz+epmzo/mT
siuMy3HnNr3qA6FFAAZWteAEGPOqDWvEfIQ0Dmd5K/6180RIWeiUzBfPbzPpu20M
WjS9js5rKOrap7kJNSWmTzVRETMSJd9qmFrDiEzzJoDmQr0crnPgt3/iNsFlMIue
aqPSw+JRC4hJ6i8TzqNp56Waq3J8BDocbmPlgDARFfqVcqbOwE0EZCdaFwEIAN87
nBFGF0wCpwAYzbXMBwIfBPxWwMf7Dzh4JeQ1yAIeOo40mURGw4TFt4jBFaf+wqao
ABH+Z1GMexypCsJz9ok3u/IgnE0r5kQbEVu7ZW9pPXf4cgIwHsXt/Bz7MrW+yGPW
e3Hm9H3t9PjCFXTLnBLdmYyU5+4z4S6GoMWWHag3xAssVtgBaENcgf/hns7zLdvk
jRIiVPpZYGfHHaw1GbbF7RaDp6g7jv80hKh75oDAbqUE9S0WDS5PQYUmwIKlH63R
1BY8j/oEciGfzBChiK85TtNMe91xwlYNt9+uzYr0nL7BhGQNKpVOfA+t3Y1rqKXM
WzdtXIdhvvRJd86c/a0AEQEAAcLBhAQYAQoADwUCZCdaFwUJAAAAAAIbLgEpCRB4
MXHLGs9ySsBdIAQZAQoABgUCZCdaFwAKCRAViO3dzbPvIGDgCACPYPcJi1FANLp4
VCXtHHZt9qjt8bOx3bqmp6OMjkwmy/F6qFapYgwZrZ90czTuN86Kvo8d8SQY7iOn
w+jOnllkK8XNBSVERTyPtOjkLlNBezHth1gp1DdSeFCJuUZxpAOmzHcNAfRwOlr9
jT14MR5YRma4fJRgzey/d+Lk2ZzAFhq5XKVtulYTsTtPzx00xzMuu9l9491SpKZe
m6SDSP9yLEk4YkwIcqgUPsrUugrIB/IpTL7sItsLA1aAmF6ZOY2tPZaZNVYvY2fr
CZENyOstwHNQb+PFI3LrOOGPfRLYkDKpCg4qFWz93iwopOvueUEmjpPEYutnwfr/
zwZFOoxuvkcIAIJ5MghsY1xYoHFEatI/0vTXDudX0sknJcT3omfBOA9gnm/P8Qzl
yYytMaisPec7AKMPnBQ28su2SwaSf5gXHfWUPTYetgh/5yoquyoRUztI0v7+WiZ4
4Jg1nIw9Nbtc5gvZa3Qlm7/R5WeJrwRspBq3sGDi7bewGJZpvSd9rPzhtZbHitvs
diuBMjuWFXH9IjVkjA6ihFCBzrApsEuF2NbjtBXsGy/NyQQIOL2/I7pIYYSgjoeE
tR/fB48K0OMKG5Odu/rBcG9vfDqaeRyTTVQHCvaGtIyfDmvublCx9NvpTO+PjCX4
ttXnrpHPLBXYeZeCvlgU++4oHIpOxjih5Wg=
=VzSK
-----END PGP PUBLIC KEY BLOCK-----"